### PR TITLE
Add various shellcheck fixes

### PR DESCRIPTION
**Pull request by pid1**
We suppress SC2129 on line 15 as I think readability outweighs the benefit here, but I'm happy to make modifications if desired.

### CODE REVIEW

**Comment by seagull** [comment]
Line 84, your version pipes "true" to the ._insu file.
The Red Canary writeup makes it clear that the inoculation file is zero bytes; piping a value to the file may cause the inoculation procedure to become ineffective.

**Comment by Datto-StanLee** [comment]
Line 84, your version pipes "true" to the ._insu file.
The Red Canary writeup makes it clear that the inoculation file is zero bytes; piping a value to the file may cause the inoculation procedure to become ineffective.

**Comment by pid1** [comment]
`true` doesn't send any output to the file, so these are equivalent implementations. You're going to get the same empty file either way.

```
bash-3.2$ true > foo
bash-3.2$ file foo
foo: empty
bash-3.2$ ls -lah foo
-rw-r--r--  1 j  staff     0B Feb 25 08:08 foo
bash-3.2$ > foo
bash-3.2$ file foo
foo: empty
bash-3.2$ ls -lah foo
-rw-r--r--  1 j  staff     0B Feb 25 08:08 foo
bash-3.2$
```

**Comment by Datto-StanLee** [comment]
I stand corrected, thank you for explaining.

**Comment by pid1** [comment]
Could this be merged?

**Comment by pid1** [comment]
@Datto-StanLee Ping on the above.

**Comment by Datto-StanLee** [comment]
Hi, I don't think I have authorisation to do this. Heckel may be able to sign-off on it.

**Pull request closed without merging**
